---
version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3.9-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    networks:
      - rabbitmq_net

  origin:
    container_name: 'origin'
    build:
      context: .
      dockerfile: orig/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - EXCHANGE=compse140
      - ROUTING_KEY=o
      - TEST_QUEUE=obse_i
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  intermediate:
    container_name: 'intermediate'
    build:
      context: .
      dockerfile: imed/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - EXCHANGE=compse140
      - QUEUE=imed
      - ROUTING_KEY_READ=o
      - ROUTING_KEY_WRITE=i
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  observer:
    container_name: 'observer'
    build:
      context: .
      dockerfile: obse/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - EXCHANGE=compse140
      - QUEUE_1=obse_o
      - QUEUE_2=obse_i
      - ROUTING_KEY_1=o
      - ROUTING_KEY_2=i
      - FILE=/opt/data/log.txt
    volumes:
      - ./data/:/opt/data/
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  httpserver:
    container_name: 'httpserver'
    build:
      context: httpserv/
    ports:
      - 8080:80
    volumes: 
      - ./data/:/etc/nginx/html/
    depends_on:
      - rabbitmq

  redis:
    image: redis:7.0-alpine
    container_name: 'redis'
    networks:
      - rabbitmq_net

  api-gw:
    container_name: api-gw
    build:
      context: .
      dockerfile: api-gw/Dockerfile
    ports:
      - 8083:8083
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - EXCHANGE=compse140
      - QUEUE=state
      - ROUTING_KEY=#
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
  