---
version: "3.4"

services:
  redis:
    image: redis:7.0-alpine
    container_name: 'redis'

  api-gw:
    container_name: api-gw
    build:
      context: .
      dockerfile: api-gw/Dockerfile
    environment:
      - REDIS_HOST=redis
      - NGINX_HOST=httpserver
    depends_on:
      - redis

  httpserver:
    container_name: 'httpserver'
    build:
      context: httpserv/
    volumes:
      - ./tests/test-data/:/etc/nginx/html/

  pytest:
    container_name: 'pytest'
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - api-gw
      - httpserver
      - redis
